### ISSUE TITLE
Question about Beat Detection

### ISSUE THREAD

**Issue by JustinYuu** [L-YeZhu/CDCD#3]
Hi, I am curious about the computation procedure of beat detection. It seems that the beats are computed by extracting the local maximums of the onset envelopes via librosa, which is more accurate to be regarded as the auditory rhythms from my own perspective. Since the librosa library also includes the official implementation of beat detection (librosa.beat.beat_track), which picks peaks in onset strength approximately consistent with estimated tempo, I wonder if the beat detection methods in the paper have a certain rationale for the dance-to-music scenarios, or if computing the hit rate of the onset maximums can reflect the performance of music generation more precisely? Thanks.

**Comment by L-YeZhu** [comment]
Hi, thank you for the question!
We used the librosa.onset.onset_detect for the beat detection, my primary motivation for this choice is based on the inspiration from the previous music-to-dance generation works, in which some existing works on the inverse direction also use the onset strength to define the acoustic beats. However, it is interesting to consider the other methods to detect the beats as well, as you mentioned, the librosa.beat.beat_track. I have not conducted a comprehensive comparison between these methods to see which one is more precise, but would like to discuss if you have further updates!
