### ISSUE TITLE
Beat Coverage Rate

### ISSUE THREAD

**Issue by JustinYuu** [L-YeZhu/CDCD#4]
Hi, I have some doubts about the usage of the beat coverage rate. As you mentioned in the D2M-GAN paper, the beat coverage rate is computed as the division of the generated beat number by the original beat number. From my point of view, this restricts the generated music from including too many beat keypoints (which has a high beat hit rate but results in poor performance). Under these preliminaries, I have two main questions.
1. The beat coverage rate can easily exceed 1 if the generated music has more beat keypoints than the original music, but I cannot find any beat coverage rate that is bigger than 1 both in the D2M-GAN and CDCD papers and I wonder the reason. By the way, in this case, is it true that the performance is better if the beat coverage rate is closer to 1 rather than bigger?
2. It seems that the final beat coverage rate is computed as the average of all samples. However, if a test set has two samples, of which the beat coverage rate is 0.5 and 1.5, respectively. In this case, the final beat coverage rate is 1, which seems to be perfect under this evaluation metric yet each sample performs unsatisfactorily. How to prevent such a phenomenon when using this evaluation metric?

I would appreciate it if you could figure out my misunderstanding regarding the beat coverage rate, and I'd like to have a further discussion about the evaluation of music beats/rhythms.

**Comment by JustinYuu** [comment]
Maybe the bit coverage rate could be computed by dividing the aligned beats by the total beats from the generated music (B_a / B_g), by which the beat coverage rate and the beat hit rate play the roles of recall and precision, respectively.

**Comment by L-YeZhu** [comment]
Hi, thank you again for the questions!
1. I agree that the beat coverage score may exceed 1 in some cases, despite the fact we did not observe this when calculating the overall scores for all the samples in both D2M-GAN and CDCD (but this may happen to certain specific samples). It makes sense to consider the score to be better when close to 1 rather than bigger.
2. It is a good suggestion to compute the score via (B_a/B_g) to mitigate the situations you mentioned.

Feel free to contact me for further discussions!

**Comment by JustinYuu** [comment]
Hi, thanks for your detailed response.
For the beat coverage score, under the circumstance that I reproduce,  the ground-truth onset peaks are likely to be all-one vectors for any two-second videos, which can explain why the beat coverage rate did not exceed 1. I think the onset detection function accounts for this phenomenon since the onset detection is second-wise rather than frame-wise. When setting `librosa.onset.onset_detect(x, sr=sr, wait=1, delta=0.2, pre_avg=1, post_avg=1, post_max=1, units='time')`, the resulted onset peaks are somewhat fine-grained so that there is at least one onset peak in each second for two-second videos, while the onset peaks are relatively sparse when the video length is longer, such as 20 seconds or longer. In my own opinion, I think the second-wise units may be not suitable for short-length videos, yet requiring the alignment of the frame-level onset peaks seems too harsh for the generated music, thus I am still finding a satisfying trade-off between these two options to get a more reasonable metric. I have also tried the version of Visual Rhythm and Beats as [here](https://github.com/abedavis/visbeat/blob/e6b7c5da1d2007b98fd53ba4b5ca6d58c75f17c0/visbeat/Audio.py#L570), but still resulting in all-one vectors for 2-second videos. Happily, I do find a satisfactory solution for longer videos, which is setting `librosa.onset.onset_detect(x, sr=sr, wait=1, delta=0.2, pre_avg=2, post_avg=2, pre_max=2, post_max=2, units='time')` to make the generated onset peaks spans uniformly into the entire music sequence.

**Comment by L-YeZhu** [comment]
Hi, thank you for your efforts and for the very helpful follow-up! Great to know about the details in terms of the beats scores.
