### ISSUE TITLE
Inference Cub

### ISSUE THREAD

**Issue by gcdYIKASFVGUSI** [L-YeZhu/CDCD#6]
Hello,Do you have inference cub.py code?

**Comment by L-YeZhu** [comment]
Hi, I have added the inference_cub.py. Let me know if there are further questions!

**Comment by gcdYIKASFVGUSI** [comment]
陈思羽：已收到您的来信，谢谢！

**Comment by gcdYIKASFVGUSI** [comment]
> Hi, I have added the inference_cub.py. Let me know if there are further questions!

 Thank you very much for the quick response and the great explanation!
