### ISSUE TITLE
aist_s6 data

### ISSUE THREAD

**Issue by yimengliu0216** [L-YeZhu/CDCD#8]
Hi, 
Thanks for your excellent work. I wonder how you processed the `aist_s6` data? Do you plan to release it? 
Thanks!

**Comment by L-YeZhu** [comment]
Hi, 
Could you try this [link](https://drive.google.com/drive/folders/1tEAn8sTkSg7GLanF2IVIYBmK_RvfgZHX?usp=share_link) for the s6 data?

**Comment by yimengliu0216** [comment]
Thanks very much!
